
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author home
 */
public class TaskApp extends javax.swing.JFrame {

    /**
     * Creates new form MainTask
     */
    public TaskApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        status = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        home_page = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        pending_counter = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        completed_counter = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        task_search_home = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        task_add = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        new_task_status = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        new_task = new javax.swing.JTextField();
        new_task_deadline = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        task_edit = new javax.swing.JPanel();
        jLabel107 = new javax.swing.JLabel();
        task_search_name_edit = new javax.swing.JTextField();
        task_edit_name = new javax.swing.JTextField();
        task_edit_status = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        task_update_button_ = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        task_edit_deadline = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        task_delete = new javax.swing.JPanel();
        task_update_button_1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        task_search_name_delete = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        pending_counter_delete = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        completed_counter_delete = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        database = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 0));
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/time_management_30px.png"))); // NOI18N
        jLabel53.setText("Task");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Edit Task");

        home.setBackground(new java.awt.Color(0, 0, 255));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home Page_30px.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(0, 0, 255));
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_property_30px.png"))); // NOI18N
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(0, 0, 255));
        delete.setForeground(new java.awt.Color(0, 0, 255));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_document_30px.png"))); // NOI18N
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        status.setBackground(new java.awt.Color(51, 0, 255));
        status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_30px.png"))); // NOI18N
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(0, 0, 255));
        logout.setForeground(new java.awt.Color(0, 0, 255));
        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Home");

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Add Task");

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Delete Task");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 78, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                .addComponent(delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel51)))
                            .addComponent(edit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(logout)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel52)
                .addGap(84, 84, 84))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel53)
                .addGap(83, 83, 83)
                .addComponent(home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(edit)
                .addGap(12, 12, 12)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(logout)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        home_page.setBackground(new java.awt.Color(255, 255, 255));

        jLabel82.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel82.setText("Task Count");

        jPanel24.setBackground(new java.awt.Color(51, 153, 255));

        pending_counter.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        pending_counter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pending_counter.setText("1");

        jLabel86.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel86.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel86.setText("Pending");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pending_counter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel86, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(pending_counter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel86)
                .addContainerGap())
        );

        jPanel25.setBackground(new java.awt.Color(51, 153, 255));

        completed_counter.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        completed_counter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completed_counter.setText("2");

        jLabel87.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel87.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel87.setText("Completed");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(completed_counter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel87, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(completed_counter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel87)
                .addContainerGap())
        );

        jLabel83.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel83.setText("Home Page");

        jLabel84.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel84.setText("My Tasks");

        task_search_home.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        task_search_home.setText("Search Task");
        task_search_home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        task_search_home.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        task_search_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                task_search_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                task_search_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                task_search_homeMouseExited(evt);
            }
        });
        task_search_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_search_homeActionPerformed(evt);
            }
        });
        task_search_home.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                task_search_homeKeyReleased(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_20px.png"))); // NOI18N

        javax.swing.GroupLayout home_pageLayout = new javax.swing.GroupLayout(home_page);
        home_page.setLayout(home_pageLayout);
        home_pageLayout.setHorizontalGroup(
            home_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pageLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(task_search_home, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_pageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel83)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel82)
                .addGap(173, 173, 173))
            .addGroup(home_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(home_pageLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(529, Short.MAX_VALUE)))
        );
        home_pageLayout.setVerticalGroup(
            home_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(home_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(home_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(home_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(home_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(task_search_home, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(home_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_pageLayout.createSequentialGroup()
                    .addContainerGap(146, Short.MAX_VALUE)
                    .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("tab1", home_page);

        task_add.setBackground(new java.awt.Color(255, 255, 255));

        jLabel109.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel109.setText("Task Add");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Task Status");

        new_task_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Completed" }));
        new_task_status.setToolTipText("");
        new_task_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_task_statusActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Task Name");

        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_30px.png"))); // NOI18N
        add_button.setText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        new_task.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_taskActionPerformed(evt);
            }
        });

        new_task_deadline.setText("October 14, 2023");
        new_task_deadline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_task_deadlineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                new_task_deadlineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                new_task_deadlineMouseExited(evt);
            }
        });
        new_task_deadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_task_deadlineActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Task Deadline");

        javax.swing.GroupLayout task_addLayout = new javax.swing.GroupLayout(task_add);
        task_add.setLayout(task_addLayout);
        task_addLayout.setHorizontalGroup(
            task_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(task_addLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(task_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(task_addLayout.createSequentialGroup()
                        .addGroup(task_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(task_addLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129)
                                .addComponent(jLabel6))
                            .addGroup(task_addLayout.createSequentialGroup()
                                .addComponent(new_task, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(new_task_status, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(new_task_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(task_addLayout.createSequentialGroup()
                        .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(440, 440, 440)
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        task_addLayout.setVerticalGroup(
            task_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(task_addLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(task_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(task_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(task_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_task_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(new_task)
                    .addComponent(new_task_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(347, 347, 347))
        );

        jTabbedPane1.addTab("tab4", task_add);

        task_edit.setBackground(new java.awt.Color(255, 255, 255));

        jLabel107.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel107.setText("Task Updating");

        task_search_name_edit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        task_search_name_edit.setText("Search Task");
        task_search_name_edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        task_search_name_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        task_search_name_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                task_search_name_editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                task_search_name_editMouseExited(evt);
            }
        });
        task_search_name_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_search_name_editActionPerformed(evt);
            }
        });
        task_search_name_edit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                task_search_name_editKeyReleased(evt);
            }
        });

        task_edit_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Completed" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Task Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Task Status");

        task_update_button_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_property_30px.png"))); // NOI18N
        task_update_button_.setText("Update");
        task_update_button_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_update_button_ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_20px.png"))); // NOI18N

        task_edit_deadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_edit_deadlineActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Task Deadline");

        javax.swing.GroupLayout task_editLayout = new javax.swing.GroupLayout(task_edit);
        task_edit.setLayout(task_editLayout);
        task_editLayout.setHorizontalGroup(
            task_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(task_editLayout.createSequentialGroup()
                .addGroup(task_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(task_editLayout.createSequentialGroup()
                        .addComponent(jLabel107)
                        .addGap(410, 410, 410)
                        .addComponent(task_update_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(task_editLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(task_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(task_edit_name, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(task_editLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(task_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(task_editLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(task_edit_status, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(task_editLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(99, 99, 99)
                        .addGroup(task_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(task_edit_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(task_editLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel8))))
                    .addGroup(task_editLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(task_search_name_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        task_editLayout.setVerticalGroup(
            task_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(task_editLayout.createSequentialGroup()
                .addGroup(task_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(task_editLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(task_update_button_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, task_editLayout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(task_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(task_search_name_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(task_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(task_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(task_editLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(task_edit_deadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(task_editLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(task_edit_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(task_editLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(task_edit_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("tab3", task_edit);

        task_delete.setBackground(new java.awt.Color(255, 255, 255));

        task_update_button_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_folder_30px.png"))); // NOI18N
        task_update_button_1.setText("Delete");
        task_update_button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_update_button_1ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_20px.png"))); // NOI18N

        jLabel108.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel108.setText("Task Count");

        task_search_name_delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        task_search_name_delete.setText("Search Task");
        task_search_name_delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        task_search_name_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        task_search_name_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                task_search_name_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                task_search_name_deleteMouseExited(evt);
            }
        });
        task_search_name_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task_search_name_deleteActionPerformed(evt);
            }
        });
        task_search_name_delete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                task_search_name_deleteKeyReleased(evt);
            }
        });

        jPanel26.setBackground(new java.awt.Color(51, 153, 255));

        pending_counter_delete.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        pending_counter_delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pending_counter_delete.setText("1");

        jLabel88.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel88.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel88.setText("Pending");

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pending_counter_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel88, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(pending_counter_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel88)
                .addGap(12, 12, 12))
        );

        jPanel27.setBackground(new java.awt.Color(51, 153, 255));

        completed_counter_delete.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        completed_counter_delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completed_counter_delete.setText("2");

        jLabel89.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel89.setText("Completed");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel89, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(completed_counter_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(completed_counter_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jLabel110.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel110.setText("Task Deletion");

        javax.swing.GroupLayout task_deleteLayout = new javax.swing.GroupLayout(task_delete);
        task_delete.setLayout(task_deleteLayout);
        task_deleteLayout.setHorizontalGroup(
            task_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(task_deleteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(task_search_name_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(task_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(task_deleteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel108)
                        .addGap(61, 61, 61))
                    .addGroup(task_deleteLayout.createSequentialGroup()
                        .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(task_update_button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(task_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(task_deleteLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel110)
                    .addContainerGap(519, Short.MAX_VALUE)))
        );
        task_deleteLayout.setVerticalGroup(
            task_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, task_deleteLayout.createSequentialGroup()
                .addGroup(task_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(task_deleteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(task_deleteLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(task_update_button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))
                .addGroup(task_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(task_deleteLayout.createSequentialGroup()
                        .addGroup(task_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, task_deleteLayout.createSequentialGroup()
                        .addGroup(task_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(task_search_name_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
            .addGroup(task_deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(task_deleteLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jLabel110, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(133, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab5", task_delete);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, -40, 710, 220));

        database.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"System Manager", "Pending", "October 15, 2023"},
                {"BookWorm", "Completed", "September 23, 2023"},
                {"Banking System", "Completed", "September 16, 2023"}
            },
            new String [] {
                "Task", "Status", "Deadline"
            }
        ));
        database.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                databaseMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(database);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 690, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?",
            "Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

        if( response == JOptionPane.YES_OPTION){
            System.out.println("Yes.. Option Selected.. ");
            dispose();
        } else if (response == JOptionPane.NO_OPTION){
            System.out.println("No.. Option Selected.. ");
            this.setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_statusActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_editActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_homeActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_deleteActionPerformed

    private void new_task_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_task_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_task_statusActionPerformed
    
    int count_completed = 2 , count_pending = 1;
    
    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        if(new_task.getText().equals("") || new_task_deadline.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please fill up all the requirments");
        } else{
            String task_name = new_task.getText();
            String task_status = (String) new_task_status.getSelectedItem();
            String task_deadline = new_task_deadline.getText();
        
        
            if(new_task_status.getSelectedItem().equals("Pending")){
                count_pending++;
                pending_counter.setText(""+count_pending);
                pending_counter_delete.setText(""+count_pending);
            } else{
                count_completed++;
                completed_counter.setText(""+count_completed);
                completed_counter_delete.setText(""+count_completed);
            }
        
            Object rowData[] = new Object[3];
            rowData[0] = task_name;
            rowData[1] = task_status;
            rowData[2] = task_deadline;
            DefaultTableModel edit_table = (DefaultTableModel)this.database.getModel();
            edit_table.addRow(rowData);
            JOptionPane.showMessageDialog(this, "Added Successfully!");
            new_task.setText("");
            new_task_deadline.setText("October 14, 2023");
        }
        
        
    }//GEN-LAST:event_add_buttonActionPerformed

    private void new_taskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_taskActionPerformed
        
    }//GEN-LAST:event_new_taskActionPerformed

    private void new_task_deadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_task_deadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_task_deadlineActionPerformed

    private void task_search_name_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task_search_name_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task_search_name_editActionPerformed

    private void task_search_name_editKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_task_search_name_editKeyReleased
        DefaultTableModel search = (DefaultTableModel) database.getModel();

        TableRowSorter<DefaultTableModel> search_data = new TableRowSorter<>(search);
        database.setRowSorter(search_data);
        search_data.setRowFilter(RowFilter.regexFilter(task_search_name_edit.getText()));

    }//GEN-LAST:event_task_search_name_editKeyReleased

    private void task_edit_deadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task_edit_deadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task_edit_deadlineActionPerformed

    private void databaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_databaseMouseClicked
        DefaultTableModel update = (DefaultTableModel)database.getModel();
        int selected = database.getSelectedRow();
        String task_name = update.getValueAt(database.getSelectedRow(), 0).toString();
        String task_deadline = update.getValueAt(database.getSelectedRow(), 2).toString();
        
        task_edit_name.setText(task_name);
        task_edit_deadline.setText(task_deadline);
    }//GEN-LAST:event_databaseMouseClicked

    private void task_search_name_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task_search_name_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task_search_name_deleteActionPerformed

    private void task_search_name_deleteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_task_search_name_deleteKeyReleased
        DefaultTableModel search = (DefaultTableModel) database.getModel();

        TableRowSorter<DefaultTableModel> search_data = new TableRowSorter<>(search);
        database.setRowSorter(search_data);
        search_data.setRowFilter(RowFilter.regexFilter(task_search_name_delete.getText()));
    }//GEN-LAST:event_task_search_name_deleteKeyReleased

    private void task_update_button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task_update_button_1ActionPerformed
        DefaultTableModel table = (DefaultTableModel)this.database.getModel();
        Object clm_Value = table.getValueAt(database.getSelectedRow(), 1);
        
        if(database.getSelectedRowCount()==1){
            if(clm_Value.equals("Pending")){
                count_pending--;
                pending_counter.setText(""+count_pending);
                pending_counter_delete.setText(""+count_pending);
                
            }else{
                count_completed--;
                completed_counter.setText(""+count_completed);
                completed_counter_delete.setText(""+count_completed);
            }
            table.removeRow(database.getSelectedRow());
            task_edit_name.setText("");
            task_edit_deadline.setText("");
            JOptionPane.showMessageDialog(this, "Successfully Deleted");
        }else if(database.getRowCount() ==0){
                JOptionPane.showMessageDialog(this, "Database is Empty!");
        }else{
                JOptionPane.showMessageDialog(this, "Please Select Row!");
        }
    }//GEN-LAST:event_task_update_button_1ActionPerformed

    private void task_update_button_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task_update_button_ActionPerformed
        DefaultTableModel update = (DefaultTableModel)database.getModel();
        Object clm_Value = update.getValueAt(database.getSelectedRow(), 1);
        
        if(database.getSelectedRowCount()==1){
            String task_name = task_edit_name.getText();
            String task_status = (String) task_edit_status.getSelectedItem();
            String task_deadline = task_edit_deadline.getText();
            
            if(clm_Value.equals("Completed") && task_status.equals("Pending")){
                count_pending++;
                count_completed--;
                pending_counter.setText(""+count_pending);
                pending_counter_delete.setText(""+count_pending);
                completed_counter.setText(""+count_completed);
                completed_counter_delete.setText(""+count_completed);
            }else if(clm_Value.equals("Pending") && task_status.equals("Completed")){
                count_pending--;
                count_completed++;
                completed_counter.setText(""+count_completed);
                completed_counter_delete.setText(""+count_completed);
                pending_counter.setText(""+count_pending);
                pending_counter_delete.setText(""+count_pending);
            }

            
            update.setValueAt(task_name, database.getSelectedRow(), 0);
            update.setValueAt(task_status, database.getSelectedRow(), 1);
            update.setValueAt(task_deadline, database.getSelectedRow(), 2);
            
            JOptionPane.showMessageDialog(this, "Updated Successfully!");
            task_edit_name.setText("");
            task_edit_deadline.setText("");
        } else if (database.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(this, "Database is Empty!");
        } else{
            JOptionPane.showMessageDialog(this, "Please Select Row To Update");
        }
    }//GEN-LAST:event_task_update_button_ActionPerformed

    private void task_search_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task_search_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_task_search_homeActionPerformed

    private void task_search_homeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_task_search_homeKeyReleased
        DefaultTableModel search = (DefaultTableModel) database.getModel();

        TableRowSorter<DefaultTableModel> search_data = new TableRowSorter<>(search);
        database.setRowSorter(search_data);
        search_data.setRowFilter(RowFilter.regexFilter(task_search_home.getText()));

    }//GEN-LAST:event_task_search_homeKeyReleased

    private void task_search_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_task_search_homeMouseClicked
        
    }//GEN-LAST:event_task_search_homeMouseClicked

    private void task_search_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_task_search_homeMouseExited
        task_search_home.setText("Search Task");
    }//GEN-LAST:event_task_search_homeMouseExited

    private void task_search_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_task_search_homeMouseEntered
        task_search_home.setText("");
    }//GEN-LAST:event_task_search_homeMouseEntered

    private void task_search_name_editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_task_search_name_editMouseEntered
        task_search_name_edit.setText("");
    }//GEN-LAST:event_task_search_name_editMouseEntered

    private void task_search_name_editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_task_search_name_editMouseExited
        task_search_name_edit.setText("Search Task");
    }//GEN-LAST:event_task_search_name_editMouseExited

    private void new_task_deadlineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_task_deadlineMouseEntered
        new_task_deadline.setText("");
    }//GEN-LAST:event_new_task_deadlineMouseEntered

    private void new_task_deadlineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_task_deadlineMouseExited

    }//GEN-LAST:event_new_task_deadlineMouseExited

    private void new_task_deadlineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_task_deadlineMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_new_task_deadlineMouseClicked

    private void task_search_name_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_task_search_name_deleteMouseEntered
        task_search_name_delete.setText("");
    }//GEN-LAST:event_task_search_name_deleteMouseEntered

    private void task_search_name_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_task_search_name_deleteMouseExited
        task_search_name_delete.setText("Search Text");
    }//GEN-LAST:event_task_search_name_deleteMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel completed_counter;
    private javax.swing.JLabel completed_counter_delete;
    private javax.swing.JTable database;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JButton home;
    private javax.swing.JPanel home_page;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField new_task;
    private javax.swing.JTextField new_task_deadline;
    private javax.swing.JComboBox<String> new_task_status;
    private javax.swing.JLabel pending_counter;
    private javax.swing.JLabel pending_counter_delete;
    private javax.swing.JButton status;
    private javax.swing.JPanel task_add;
    private javax.swing.JPanel task_delete;
    private javax.swing.JPanel task_edit;
    private javax.swing.JTextField task_edit_deadline;
    private javax.swing.JTextField task_edit_name;
    private javax.swing.JComboBox<String> task_edit_status;
    private javax.swing.JTextField task_search_home;
    private javax.swing.JTextField task_search_name_delete;
    private javax.swing.JTextField task_search_name_edit;
    private javax.swing.JButton task_update_button_;
    private javax.swing.JButton task_update_button_1;
    // End of variables declaration//GEN-END:variables

    private String toString(int count_pending) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
